

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: my_mysql_container
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demostore
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password


  wordpress:
    depends_on:
      - db
    image: supersqa/demostore-wordpress:v2-with-backup-6.6.2
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: my_wordpress_container
    ports:
      - "7070:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: my_mysql_container:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: demostore
      SITE_URL: ${SITE_URL:-http://0.0.0.0:7070}
    entrypoint: /entrypoint-custom.sh


