

services:
  db:
    image: supersqa/demostore-mysql:v2-8.0
    restart: always
    container_name: my_mysql_container
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demostore
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password


  wordpress:
    depends_on:
      - db
    image: supersqa/demostore-wordpress:v2-6.6
    container_name: my_wordpress_container
    ports:
      - "7676:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: my_mysql_container:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: demostore
      WORDPRESS_IP: ${WORDPRESS_IP:-0.0.0.0}
    entrypoint: /entrypoint-custom.sh
